export interface CityData {
  slug: string
  name: string
  state: string
  region: string
  description: string      // 2-3 sentence city intro for SEO
  businessContext: string  // what types of businesses are common there
  landmark: string         // a well-known local landmark or context
  image: string            // Unsplash image for the city/region
}

export const cities: CityData[] = [
  {
    slug: "agartala",
    name: "Agartala",
    state: "Tripura",
    region: "Northeast India",
    description: "Agartala is the capital city of Tripura and one of the fastest-growing cities in Northeast India. With a vibrant business community and increasing internet penetration, local businesses in Agartala are rapidly discovering the power of having an online presence.",
    businessContext: "doctors, dental clinics, gyms, salons, lawyers, hotels, coaching centres, and restaurants",
    landmark: "Ujjayanta Palace",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
  },
  {
    slug: "guwahati",
    name: "Guwahati",
    state: "Assam",
    region: "Northeast India",
    description: "Guwahati is the largest city in Northeast India and the commercial gateway to the region. As the economic hub of Assam, Guwahati has thousands of local businesses competing for customers — and a strong website is what sets the best ones apart.",
    businessContext: "hospitals, clinics, gyms, salons, law firms, hotels, restaurants, and educational institutions",
    landmark: "Kamakhya Temple",
    image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&q=80",
  },
  {
    slug: "silchar",
    name: "Silchar",
    state: "Assam",
    region: "Northeast India",
    description: "Silchar is a major commercial city in the Barak Valley region of Assam. The city's growing business community includes many local enterprises that are only now beginning to build their digital presence — creating an excellent opportunity for businesses that move online first.",
    businessContext: "healthcare providers, fitness centres, salons, legal firms, coaching institutes, and retail businesses",
    landmark: "Barak River",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
  {
    slug: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    region: "Northeast India",
    description: "Shillong, the Scotland of the East, is the capital of Meghalaya and a thriving hub for tourism, education, and business. With a growing startup culture and an influx of tourists, businesses in Shillong need a strong online presence to capture both local and visiting customers.",
    businessContext: "hotels, cafes, tour operators, photographers, coaching centres, salons, and retail businesses",
    landmark: "Shillong Peak",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
  {
    slug: "imphal",
    name: "Imphal",
    state: "Manipur",
    region: "Northeast India",
    description: "Imphal is the capital city of Manipur and a city of immense cultural richness and growing economic activity. Local businesses in Imphal have a remarkable opportunity to stand out online — digital competition remains low while internet usage continues to rise rapidly.",
    businessContext: "clinics, gyms, salons, handicraft businesses, hotels, restaurants, and coaching centres",
    landmark: "Kangla Fort",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
  },
  {
    slug: "patna",
    name: "Patna",
    state: "Bihar",
    region: "East India",
    description: "Patna is one of the oldest and largest cities in India with a population of over 2 million people. Bihar's capital has a massive base of local businesses — and yet the majority still lack a proper website, making it one of the highest-opportunity markets for digital growth in the entire country.",
    businessContext: "doctors, coaching institutes, lawyers, CAs, gyms, salons, hotels, and restaurants",
    landmark: "Ganga River Ghats",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200&q=80",
  },
  {
    slug: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    region: "East India",
    description: "Ranchi is the capital of Jharkhand and one of the fastest-growing cities in Eastern India. With a rapidly expanding middle class and growing business ecosystem, Ranchi represents a significant opportunity for local businesses ready to establish their digital presence.",
    businessContext: "hospitals, clinics, coaching centres, gyms, salons, hotels, and professional services",
    landmark: "Hundru Falls",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
  {
    slug: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    region: "East India",
    description: "Bhubaneswar is one of the fastest-growing cities in India and Odisha's thriving capital. With a booming IT sector and rapidly expanding local economy, businesses in Bhubaneswar are competing hard — and a professional website is increasingly the difference between standing out and being overlooked.",
    businessContext: "IT companies, clinics, gyms, salons, real estate agencies, coaching institutes, and restaurants",
    landmark: "Lingaraj Temple",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
  },
  {
    slug: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    region: "Central India",
    description: "Raipur is the capital of Chhattisgarh and an emerging business hub in Central India. The city's business community is growing fast, and local enterprises that establish a strong online presence now are positioning themselves well ahead of the digital curve.",
    businessContext: "clinics, gyms, coaching institutes, lawyers, real estate, hotels, and retail businesses",
    landmark: "Nandanvan Zoo",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200&q=80",
  },
  {
    slug: "coimbatore",
    name: "Coimbatore",
    state: "Tamil Nadu",
    region: "South India",
    description: "Coimbatore is one of the most important industrial and commercial cities in South India, known as the Manchester of South India. With thousands of small and medium businesses across manufacturing, textiles, healthcare, and education, Coimbatore has a massive demand for professional digital presence.",
    businessContext: "manufacturers, clinics, gyms, engineering firms, coaching institutes, hotels, and restaurants",
    landmark: "Marudamalai Temple",
    image: "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=1200&q=80",
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    region: "South India",
    description: "Madurai is one of the oldest cities in India and Tamil Nadu's second-largest city. With a bustling commercial economy, thriving tourism industry, and a large population of local businesses, Madurai is a city where a professional website can deliver immediate and significant results.",
    businessContext: "temples and tourism, clinics, textiles, coaching centres, hotels, restaurants, and retail",
    landmark: "Meenakshi Amman Temple",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&q=80",
  },
  {
    slug: "nagpur",
    name: "Nagpur",
    state: "Maharashtra",
    region: "Central India",
    description: "Nagpur is Maharashtra's second capital and the geographic heart of India. Known as the Orange City, Nagpur has a diverse and growing economy with significant opportunities for local businesses to reach customers through a professional online presence.",
    businessContext: "lawyers, doctors, coaching institutes, gyms, salons, real estate agents, and restaurants",
    landmark: "Deekshabhoomi",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200&q=80",
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    region: "Central India",
    description: "Indore is the commercial capital of Madhya Pradesh and one of the cleanest cities in India. With a booming startup culture, a large student population, and an entrepreneurial business community, Indore is a highly dynamic market for businesses looking to grow their online presence.",
    businessContext: "startups, coaching centres, clinics, gyms, restaurants, real estate, and professional services",
    landmark: "Rajwada Palace",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
  },
  {
    slug: "jorhat",
    name: "Jorhat",
    state: "Assam",
    region: "Northeast India",
    description: "Jorhat is a significant city in Upper Assam and the cultural capital of the Assamese people. Known for its tea industry and educational institutions, Jorhat has a growing business community that is beginning to recognise the value of having a professional online presence.",
    businessContext: "tea estates, clinics, coaching institutes, hotels, restaurants, and retail businesses",
    landmark: "Kaziranga National Park nearby",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
  {
    slug: "dibrugarh",
    name: "Dibrugarh",
    state: "Assam",
    region: "Northeast India",
    description: "Dibrugarh is the commercial capital of Upper Assam and a major hub for the tea industry. As one of the most important cities in Eastern Assam, Dibrugarh has a strong business community that increasingly recognises the importance of digital presence for growth.",
    businessContext: "tea industry businesses, clinics, coaching centres, hotels, restaurants, and professional services",
    landmark: "Brahmaputra River",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
  },
]
